### ISSUE TITLE
Doesn't work with nested classes

### ISSUE THREAD

**Issue by VoronFX** [demigor/kindofmagic#2]
Hi! I've recently discovered that Kind of Magic doesn't process nested types. 
Is it a bug or normal behavior?
If normal then it should be noted at least on project main page.
I am not excluding that maybe I am doing something wrong so here is the code:

<pre><code>public class SomeClassComposition
{
    [Magic]
    public class ItDoesntWork : INotifyPropertyChanged
    {
        public int SomeProperty { get; set; }

        protected virtual void RaisePropertyChanged(string propertyName)
        {
            var handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        public event PropertyChangedEventHandler PropertyChanged;
    }
}

[Magic]
public class ItWork : INotifyPropertyChanged
{
    public int SomeProperty { get; set; }

    protected virtual void RaisePropertyChanged(string propertyName)
    {
        var handler = PropertyChanged;
        if (handler != null)
            handler(this, new PropertyChangedEventArgs(propertyName));
    }

    public event PropertyChangedEventHandler PropertyChanged;
}
</code></pre>

Anyway, your project is great! Thank you!
I included test project.
[KindOfMagicNestingTest.zip](https://github.com/demigor/kindofmagic/files/79026/KindOfMagicNestingTest.zip)

**Comment by demigor** [comment]
Fixed in 1.3.1
